- hosts: localhost
  vars:
    var1: 'DEBUG'
    var2: 'OPMODE'
    var3: 'IPMAPRESOLVER'
    var4: 'IPMAPSERVER'
    var5: 'KEYMAPSERVER'
    var6: 'IPPROXYETRV4'
    var7: 'IPPROXYETRV6'
    var8: 'IPV4EIDPREFFIX'
    var9: 'IPV6EIDPREFFIX'
  tasks:
  - name: OOR Debug
    blockinfile:
      dest: /etc/oor.conf
      block: |
        debug                  = {{ var1 }}
      marker: "<!-- {mark} debug -->"
      backup: no
      insertbefore: "^map-request-retries"
  - name: OOR Operation Mode
    blockinfile:
      dest: /etc/oor.conf
      block: |
        operating-mode         = {{ var2 }}
      marker: "<!-- {mark} operating-mode -->"
      backup: no
  - name: OOR Map Resolver
    blockinfile:
      dest: /etc/oor.conf
      block: |
        map-resolver        = {
                {{ var3 }}
        }
      marker: "<!-- {mark} map-resolver -->"
      backup: no

  - name: OOR Map Server
    blockinfile:
      dest: /etc/oor.conf
      block: |
        map-server {
                address        = {{ var4 }}
                key-type       = 1
                key            = {{ var5 }}
                proxy-reply    = off
        }
      marker: "<!-- {mark} map-server -->"
      backup: no

  - name: OOR Proxy ETR IPV4 enabled
    when: var6  != '-'
    blockinfile:
      dest: /etc/oor.conf
      state: present
      block: |
        proxy-etr-ipv4 {
                address     = {{ var6 }}
                priority    = 1
                weight      = 100
        }
      marker: "<!-- {mark} proxy-etr-ipv4 -->"
      backup: no
  - name: OOR Proxy ETR IPV4 disabled
    when: var6  == '-'
    blockinfile:
      dest: /etc/oor.conf
      state: absent
      marker: "<!-- {mark} proxy-etr-ipv4 -->"
      backup: no

  - name: OOR Proxy ETR IPV6 enabled
    when: var7  != '-'
    blockinfile:
      dest: /etc/oor.conf
      state: present
      block: |
        proxy-etr-ipv6 {
                address     = {{ var7 }}
                priority    = 1
                weight      = 100
        }
      marker: "<!-- {mark} proxy-etr-ipv6 -->"
      backup: no
  - name: OOR Proxy ETR IPV6 disabled
    when: var7  == '-'
    blockinfile:
      dest: /etc/oor.conf
      state: absent
      marker: "<!-- {mark} proxy-etr-ipv6 -->"
      backup: no


  - name: OOR Database Mapping IPV4 enabled
    when: var8  != '-'
    blockinfile:
      dest: /etc/oor.conf
      state: present
      block: |
        database-mapping {
            eid-prefix          = {{ var8 }}
            iid                 = 0
            rloc-iface{
                interface       = eth0
                ip_version      = 4
                priority        = 1
                weight          = 100
            }
        }
      marker: "<!-- {mark} database-mappingv4 -->"
      backup: no
  - name: OOR Database Mapping IPV4 disabled
    when: var8 == '-'
    blockinfile:
      dest: /etc/oor.conf
      state: absent
      marker: "<!-- {mark} database-mappingv4 -->"
      backup: no


  - name: OOR Database Mapping IPV6 enabled
    when: var9  != '-'
    blockinfile:
      dest: /etc/oor.conf
      block: |
        database-mapping {
            eid-prefix          = {{ var9 }}
            iid                 = 0
            rloc-iface{
                interface       = eth0
                ip_version      = 4
                priority        = 1
                weight          = 100
            }
        }
      marker: "<!-- {mark} database-mappingv6 -->"
      backup: no
  - name: OOR Database Mapping IPV6 disabled
    when: var9  == '-'
    blockinfile:
      dest: /etc/oor.conf
      state: absent
      marker: "<!-- {mark} database-mappingv6 -->"
      backup: no